basePath: /
definitions:
  handlers.Reservation:
    properties:
      company:
        type: string
      created_at:
        type: string
      end_time:
        type: string
      final_price:
        type: integer
      id:
        type: string
      name:
        type: string
      participants:
        type: integer
      phone:
        type: string
      room:
        $ref: '#/definitions/handlers.Rooms'
      room_price:
        type: integer
      snack:
        $ref: '#/definitions/handlers.Snacks'
      start_time:
        type: string
      status:
        type: string
      total_snack:
        type: integer
      updated_at:
        type: string
      user:
        $ref: '#/definitions/handlers.User'
    type: object
  handlers.Room:
    properties:
      capacity:
        type: integer
      id:
        type: string
      name:
        type: string
      price:
        type: integer
      type:
        type: string
    type: object
  handlers.Rooms:
    properties:
      capacity:
        type: integer
      id:
        type: string
      name:
        type: string
      price:
        type: integer
      type:
        type: string
    type: object
  handlers.Snacks:
    properties:
      category:
        type: string
      id:
        type: string
      name:
        type: string
      package:
        type: string
      price:
        type: string
    type: object
  handlers.User:
    properties:
      email:
        type: string
      id:
        type: string
      image_id:
        type: string
      language:
        type: string
      password:
        type: string
      role:
        type: string
      status:
        type: boolean
      username:
        type: string
    type: object
  handlers.UserInput:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - confirm_password
    - email
    - password
    - username
    type: object
  handlers.UserLogin:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  handlers.UserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      image_id:
        type: string
      language:
        type: string
      password:
        type: string
      role:
        type: string
      status:
        type: boolean
      username:
        type: string
    type: object
  handlers.response:
    properties:
      data:
        items:
          $ref: '#/definitions/handlers.UserResponse'
        type: array
      message:
        type: string
    type: object
  handlers.responseRoom:
    properties:
      data:
        items:
          $ref: '#/definitions/handlers.Room'
        type: array
      message:
        type: string
    type: object
host: localhost:7000
info:
  contact: {}
  description: This is documentation API from Swagger
  termsOfService: http://swagger.io/terms/
  title: Swagger MeetApp By Sinau Koding API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 'Login user menggunakan email dan password, email: mail@mail.com,
        password: password123'
      parameters:
      - description: User login details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handlers.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request payload
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Invalid credentials
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handlers.UserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Register a new user
      tags:
      - auth
  /reservations:
    get:
      consumes:
      - application/json
      description: Retrieve all reservations in the system
      parameters:
      - description: Filter by status
        in: query
        name: status
        type: string
      - description: Filter by room type
        in: query
        name: room_type
        type: string
      - description: Filter by start date (YYYY-MM-DD)
        in: query
        name: start_date
        type: string
      - description: Filter by end date (YYYY-MM-DD)
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.Reservation'
            type: array
      summary: Get all reservations
      tags:
      - reservations
    post:
      consumes:
      - application/json
      description: Create a new reservation
      parameters:
      - description: Reservation details
        in: body
        name: reservation
        required: true
        schema:
          $ref: '#/definitions/handlers.Reservation'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new reservation
      tags:
      - reservations
  /reservations/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve a reservation by its ID
      parameters:
      - description: Reservation ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Reservation'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a reservation by ID
      tags:
      - reservations
    put:
      consumes:
      - application/json
      description: Edit a reservation
      parameters:
      - description: Reservation ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Edit a reservation
      tags:
      - reservations
  /rooms:
    get:
      description: Retrieve all rooms in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.responseRoom'
      summary: Get all rooms
      tags:
      - rooms
    post:
      consumes:
      - application/json
      description: Create a new room
      parameters:
      - description: Room details
        in: body
        name: room
        required: true
        schema:
          $ref: '#/definitions/handlers.Room'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.Room'
      summary: Create a new room
      tags:
      - rooms
  /rooms/{id}:
    delete:
      description: Delete a room by ID
      parameters:
      - description: Room ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Delete a room by ID
      tags:
      - rooms
    get:
      description: Get a room by ID
      parameters:
      - description: Room ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.responseRoom'
      summary: Get a room by ID
      tags:
      - rooms
    put:
      consumes:
      - application/json
      description: Update a room by ID
      parameters:
      - description: Room ID
        in: path
        name: id
        required: true
        type: string
      - description: Room details
        in: body
        name: room
        required: true
        schema:
          $ref: '#/definitions/handlers.Room'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.responseRoom'
      summary: Update a room by ID
      tags:
      - rooms
  /snack:
    get:
      description: Get Snack
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get Snack
      tags:
      - Snack
    post:
      description: Create Snack
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create Snack
      tags:
      - Snack
  /users:
    get:
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.response'
      summary: Get all users
      tags:
      - users
  /users/{id}:
    delete:
      description: Delete user by ID
      parameters:
      - description: Reservation ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.response'
      summary: Delete user by ID
      tags:
      - users
    get:
      description: Get user by ID
      parameters:
      - description: Reservation ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.response'
      summary: Get user by ID
      tags:
      - users
    put:
      description: Update user by ID
      parameters:
      - description: Reservation ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.response'
      summary: Update user by ID
      tags:
      - users
swagger: "2.0"
