info:
  contact: {}
  description: This is docomentation api from swagger
  termsOfService: http://swagger.io/terms/
  title: Swagger MeetApp By Sinau Koding API
  version: "1.0"
paths: {}
swagger: "2.0"
